apiVersion: v1
kind: Pod
metadata:
  name: pod01
  labels:
    app: primeiro_pod
spec:
  containers:
    - name: container-pod-1
      image: nginx:latest
      ports:
        - containerPort: 80